import { NOTIFICATION_TYPE_LEAVE_APPROVED, NOTIFICATION_TYPE_LEAVE_CANCELLED, NOTIFICATION_TYPE_LEAVE_REQUESTED, NOTIFICATION_TYPE_LEAVE_REJECTED, NOTIFICATION_TYPE_LEAVE_SUBMITTED } from "../../utils/constant";

export enum NotificationType {
  LEAVE_REQUESTED = NOTIFICATION_TYPE_LEAVE_REQUESTED,
  LEAVE_APPROVED = NOTIFICATION_TYPE_LEAVE_APPROVED,
  LEAVE_REJECTED = NOTIFICATION_TYPE_LEAVE_REJECTED,
  LEAVE_CANCELLED = NOTIFICATION_TYPE_LEAVE_CANCELLED,
  LEAVE_SUBMITTED = NOTIFICATION_TYPE_LEAVE_SUBMITTED,
}

export interface CreateNotificationDto {
  tenantId: string;
  recipients: string[];
  actorId?: string;
  title: string;
  message: string;
  entityType: NotificationType;
  entityId?: string;
}